service: audio2video

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 900
  iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:GetObject
    Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  mkvideo:
    handler: handler.mkvideo
    events:
      - s3: ${self:custom.bucket}
    layers:
      - {Ref: FfmpegLambdaLayer}

layers:
  ffmpeg:
    path: layer

custom:
  bucket: audio2video-files-k6b4a
