service: audio2video

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 900
  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:GetObject
    - s3:PutObject
    Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  mkvideo:
    handler: handler.mkvideo
    events:
    - s3:
        bucket: ${self:custom.bucket}
        event: s3:ObjectCreated:*
        rules:
        - prefix: uploads/
        - suffix: .mp3
    layers:
      - {Ref: FfmpegLambdaLayer}

layers:
  ffmpeg:
    path: layer

custom:
  bucket: audio2video
